repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: ruff check --force-exclude --fix
        language: python
        types_or: [python, pyi, jupyter]
      - id: ruff-format
        name: ruff format
        entry: ruff format --force-exclude
        language: python
        types_or: [python, pyi, jupyter]
