repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: ruff check --force-exclude --fix
        language: python
        types_or: [python, pyi, jupyter]
        additional_dependencies: [ruff]
      - id: ruff-format
        name: ruff format
        entry: ruff format --force-exclude
        language: python
        types_or: [python, pyi, jupyter]
        additional_dependencies: [ruff]
      - id: ty-check
        name: ty check
        entry: ty check
        language: python
        types_or: [python, pyi]
        additional_dependencies: [ty]
        pass_filenames: false
      - id: check-language
        name: check language
        entry: bash scripts/check-language.sh
        language: system
        pass_filenames: false
        always_run: true
