FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim AS builder
ENV UV_COMPILE_BYTECODE=1
ENV UV_LINK_MODE=copy
ENV SHELL /bin/bash
WORKDIR /app
RUN apt update && apt install -y --no-install-recommends \
    openssh-client \
    git \
    && rm -rf /var/lib/apt/lists/*
RUN mkdir -p /app && chown 1000:1000 /app
RUN addgroup --system --gid 1000 appuser \
    && adduser --home /home/appuser --system --uid 1000 --gid 1000 appuser
USER appuser
RUN --mount=type=cache,target=/home/appuser/.cache/uv,uid=1000,gid=1000 \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --frozen --no-install-project --no-dev
ADD . /app
RUN --mount=type=cache,target=/home/appuser/.cache/uv,uid=1000,gid=1000 \
    uv sync --frozen --no-dev
ENV PATH="/app/.venv/bin:$PATH"
# CMD ["fastapi", "dev", "--host", "0.0.0.0", "/app/src/uv_docker_example"]