name: textual-code-devcontainer

services:
  textual-code-devcontainer-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: "no"
    command: sleep infinity
    init: true
    volumes:
      - ../:/project
    environment:
      - CLAUDE_CONFIG_DIR=/home/appuser/.claude
    env_file:
      - path: ../.env
        required: false
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "100"
        compress: "true"
