#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
if [[ "${TRACE-0}" == "1" ]]; then
    set -o xtrace
fi

if [[ "${1-}" =~ ^-*h(elp)?$ ]]; then
    echo 'Usage: ./scripts/download-libs-docs.sh

Downloads Textual framework documentation, builds it with mkdocs-llmstxt,
and saves per-page markdown files to docs/libs/textual/.

Uses the same version tag as the installed package.
Requires: git, uv

'
    exit
fi

cd "$(dirname "$0")/.."

DEST_DIR="docs/libs/textual"
REPO_URL="https://github.com/Textualize/textual.git"
WORK_DIR="$(mktemp --directory)"

cleanup() {
    rm -rf "$WORK_DIR"
}
trap cleanup EXIT

# Resolve installed Textual version
TEXTUAL_VERSION="$(uv run python -c "import textual; print(textual.__version__)")"
GIT_TAG="v${TEXTUAL_VERSION}"
echo "Detected Textual version: ${TEXTUAL_VERSION} (tag: ${GIT_TAG})" >&2

echo "Cloning Textual repo (tag ${GIT_TAG})..." >&2
git clone \
    --depth=1 \
    --branch "${GIT_TAG}" \
    "$REPO_URL" \
    "$WORK_DIR/repo"

echo "Creating isolated venv..." >&2
uv venv "$WORK_DIR/.venv"

echo "Installing dependencies..." >&2
uv pip install --python "$WORK_DIR/.venv/bin/python" \
    "$WORK_DIR/repo" \
    mkdocs \
    mkdocs-material \
    "mkdocstrings[python]" \
    mkdocstrings-python \
    pymdown-extensions \
    mkdocs-autorefs \
    mkdocs-exclude \
    mkdocs-llmstxt

echo "Writing custom mkdocs-build.yml..." >&2
cat > "$WORK_DIR/repo/mkdocs-build.yml" << 'EOF'
INHERIT: mkdocs-nav.yml

site_name: Textual
site_url: http://localhost/
docs_dir: docs

theme:
  name: material

markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - meta
  - footnotes
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: textual
          class: textual
          format: !!python/name:textual._doc.format_svg
        - name: rich
          class: rich
          format: !!python/name:textual._doc.rich
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
  - md_in_html

plugins:
  - search:
  - autorefs:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths:
            - src
          options:
            show_source: false
            filters:
              - "!^_"
              - "^__init__$"
  - llmstxt:
      sections:
        Textual:
          - "**"
  - exclude:
      glob:
        - "**/_template.md"
        - "snippets/*"
EOF

echo "Building docs..." >&2
cd "$WORK_DIR/repo"
"$WORK_DIR/.venv/bin/mkdocs" build \
    --config-file mkdocs-build.yml \
    --site-dir "$WORK_DIR/site"
cd - > /dev/null

echo "Copying per-page markdown files to $DEST_DIR/..." >&2
if [[ ! -f "$WORK_DIR/site/llms.txt" ]]; then
    echo "Error: llms.txt was not generated. Check mkdocs-llmstxt plugin config." >&2
    exit 1
fi

# Count .md files generated by the plugin (excludes llms.txt itself)
MD_COUNT="$(find "$WORK_DIR/site" -name '*.md' | wc -l)"
if [[ "$MD_COUNT" -eq 0 ]]; then
    echo "Error: no per-page .md files found in site directory." >&2
    exit 1
fi

rm -rf "$DEST_DIR"
mkdir -p "$DEST_DIR"

# Copy all .md files preserving directory structure
find "$WORK_DIR/site" -name '*.md' -print0 \
    | while IFS= read -r -d '' src; do
        rel="${src#"$WORK_DIR/site/"}"
        dest="$DEST_DIR/$rel"
        mkdir -p "$(dirname "$dest")"
        cp "$src" "$dest"
    done

echo "Done. Textual ${TEXTUAL_VERSION} docs saved to $DEST_DIR/ (${MD_COUNT} files)" >&2
